#/bin/bash
#PBS -j oe
#PBS -q omp
#PBS -l select=1:ncpus=5:mem=6g
#PBS -l walltime=00:120:00
#PBS -m n
#PBS -N session_2017_11_19_paddle_Black_Rocks
#PBS -o ./results_txt/output_session_2017_11_19_paddle_Black_Rocks.txt
#PBS -S /bin/bash

signal_handler() {
	pkill --parent "${$}"
}

trap signal_handler EXIT
cd /home3/datahome/aboyer/Documents/seatizen-to-zenodo/multilabelTest

. /appli/anaconda/latest/etc/profile.d/conda.sh
conda activate /home/datawork-iot-nos/Seatizen/conda-env/jacques_cpu
python /home3/datahome/aboyer/Documents/seatizen-to-zenodo/multilabelTest/folders_preparation.py
conda deactivate
