 -q omp
#PBS -l select=1:ncpus=2:mem=3g
#PBS -l walltime=00:45:00
#PBS -J 1-42
#PBS -m n
#PBS -N zipSessionsFolders
#PBS -S /bin/bash

signal_handler() {
	pkill --parent "${$}"
}

trap signal_handler EXIT

cd /home3/datahome/aboyer/Documents/seatizen-to-zenodo/multilabelTest

. /appli/anaconda/latest/etc/profile.d/conda.sh
conda activate /home/datawork-iot-nos/Seatizen/conda-env/jacques_cpu
python /home3/datahome/aboyer/Documents/seatizen-to-zenodo/multilabelTest/zip_folders.py --session-index $PBS_ARRAY_INDEX
conda deactivate

qstat -f $PBS_JOBID

